"""First migration.

Revision ID: fc68dd4aac8f
Revises: 
Create Date: 2022-04-14 19:37:24.559738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc68dd4aac8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone_no', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('creation_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_last_name'), ['last_name'], unique=False)

    op.create_table('orphanage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('students', sa.Integer(), nullable=True),
    sa.Column('phone_no', sa.String(length=20), nullable=True),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('activities', sa.Text(), nullable=True),
    sa.Column('paypal_info', sa.JSON(), nullable=True),
    sa.Column('social_media_links', sa.JSON(), nullable=True),
    sa.Column('story', sa.Text(), nullable=True),
    sa.Column('money_uses', sa.Text(), nullable=True),
    sa.Column('photos_links', sa.JSON(), nullable=True),
    sa.Column('bank_info', sa.Text(), nullable=True),
    sa.Column('actId', sa.String(length=120), nullable=True),
    sa.Column('acttype', sa.String(length=6), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orphanage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orphanage_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_orphanage_name'), ['name'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('phone_no', sa.String(length=20), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('donation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donation_time', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('orph_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['orph_id'], ['orphanage.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donation_donation_time'), ['donation_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donation_donation_time'))

    op.drop_table('donation')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_token'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('orphanage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orphanage_name'))
        batch_op.drop_index(batch_op.f('ix_orphanage_email'))

    op.drop_table('orphanage')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_last_name'))
        batch_op.drop_index(batch_op.f('ix_message_first_name'))

    op.drop_table('message')
    # ### end Alembic commands ###
